# Generated by Django 6.0.1 on 2026-06-10 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('merit_state_code', models.CharField(max_length=10)),
                ('merit_url', models.URLField(max_length=500)),
                ('model_path', models.CharField(max_length=500)),
                ('fallback_demand_mw', models.FloatField(default=14500.0)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('cities', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('actual_demand', models.FloatField(blank=True, null=True)),
                ('predicted_demand', models.FloatField()),
                ('temp_weighted', models.FloatField()),
                ('month', models.IntegerField()),
                ('holiday', models.IntegerField()),
                ('is_weekend', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('y_lag_1', models.FloatField()),
                ('y_lag_24h', models.FloatField()),
                ('y_lag_7d', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='states.state')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['state', 'timestamp'], name='states_pred_state_i_54ac05_idx')],
            },
        ),
        migrations.CreateModel(
            name='DemandReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('demand_mw', models.FloatField()),
                ('source', models.CharField(choices=[('api', 'MERIT API'), ('predicted', 'Predicted'), ('import', 'Imported')], default='api', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_readings', to='states.state')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['state', 'timestamp'], name='states_dema_state_i_1f5f64_idx')],
                'unique_together': {('state', 'timestamp')},
            },
        ),
    ]
