# Generated by Django 6.0.1 on 2026-06-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="merit_urls",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
